//! Rust code completion domain.
//!
//! Each prompt is the prefix of a tiny Rust program with a placeholder; the
//! model produces a continuation; the verifier writes prompt+completion to a
//! scratch project's `src/main.rs` and runs `cargo run` (or `cargo check` if
//! `RustCodeDomain.run_program` is false).
//!
//! The scratch project must already exist on disk — it is NOT created by
//! this domain (we don't want the verifier to mutate parent directories at
//! runtime). Use [`RustCodeDomain::ensure_scratch_project`] once at startup.
//!
//! Phase 2.5 ships only the simplest "fill the right-hand side of an
//! `assert_eq!`" task; the surface area is intentionally small so the
//! verifier semantics are easy to test.

use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use rand::rngs::StdRng;
use rand::Rng;

use super::Domain;
use crate::types::Verdict;

#[derive(Debug, Clone)]
pub struct RustChallenge {
    /// Free-form description (used as a comment in the generated file).
    pub name: &'static str,
    /// Prompt — code preceding the completion.
    pub prompt: &'static str,
    /// Suffix appended after the completion before compilation.
    pub suffix: &'static str,
}

pub const DEFAULT_CHALLENGES: &[RustChallenge] = &[
    RustChallenge {
        name: "add_two_three",
        prompt: "fn main() { assert_eq!(",
        suffix: ", 5); }\n",
    },
    RustChallenge {
        name: "double_seven",
        prompt: "fn main() { assert_eq!(",
        suffix: ", 14); }\n",
    },
    RustChallenge {
        name: "string_len",
        prompt: r#"fn main() { assert_eq!("#,
        suffix: r#", 5); }
"#,
    },
];

pub struct RustCodeDomain {
    pub scratch_dir: PathBuf,
    pub challenges: &'static [RustChallenge],
    /// `false`: only `cargo check` (faster, doesn't run the binary).
    /// `true`: `cargo run` + check exit status.
    pub run_program: bool,
    pub timeout: Duration,
    /// cargo invocations are serialized — they all write to the same
    /// `src/main.rs`.
    write_lock: Mutex<()>,
}

impl RustCodeDomain {
    pub fn new(scratch_dir: impl Into<PathBuf>) -> Self {
        Self {
            scratch_dir: scratch_dir.into(),
            challenges: DEFAULT_CHALLENGES,
            run_program: true,
            timeout: Duration::from_secs(30),
            write_lock: Mutex::new(()),
        }
    }

    /// Create a `Cargo.toml` + `src/main.rs` skeleton. Idempotent.
    pub fn ensure_scratch_project(&self) -> std::io::Result<()> {
        fs::create_dir_all(self.scratch_dir.join("src"))?;
        let cargo = self.scratch_dir.join("Cargo.toml");
        if !cargo.exists() {
            let mut f = fs::File::create(&cargo)?;
            writeln!(
                f,
                "[package]\nname = \"scratch\"\nversion = \"0.0.0\"\nedition = \"2021\"\n[dependencies]\n"
            )?;
        }
        let main = self.scratch_dir.join("src/main.rs");
        if !main.exists() {
            fs::write(&main, "fn main() {}\n")?;
        }
        Ok(())
    }

    fn challenge_for_prompt(&self, prompt: &str) -> Option<&RustChallenge> {
        self.challenges.iter().find(|c| c.prompt == prompt)
    }

    fn write_program(&self, prompt: &str, completion: &str, suffix: &str) -> std::io::Result<()> {
        let _guard = self.write_lock.lock().expect("write_lock poisoned");
        let path = self.scratch_dir.join("src/main.rs");
        let mut full = String::with_capacity(prompt.len() + completion.len() + suffix.len() + 32);
        full.push_str("// auto-generated by RustCodeDomain — do not edit\n");
        full.push_str(prompt);
        full.push_str(completion);
        full.push_str(suffix);
        fs::write(path, full)
    }

    fn run_cargo(&self, run: bool) -> std::io::Result<RunOutcome> {
        let start = Instant::now();
        let mut cmd = Command::new("cargo");
        cmd.arg(if run { "run" } else { "check" })
            .arg("--quiet")
            .arg("--offline")
            .current_dir(&self.scratch_dir);
        let output = cmd.output()?;
        Ok(RunOutcome {
            success: output.status.success(),
            elapsed: start.elapsed(),
            stderr_tail: tail_lines(&String::from_utf8_lossy(&output.stderr), 5),
        })
    }
}

#[derive(Debug)]
struct RunOutcome {
    success: bool,
    elapsed: Duration,
    stderr_tail: String,
}

fn tail_lines(s: &str, n: usize) -> String {
    let lines: Vec<&str> = s.lines().collect();
    let take = lines.len().saturating_sub(n);
    lines[take..].join("\n")
}

impl Domain for RustCodeDomain {
    fn sample_prompt(&self, rng: &mut StdRng) -> String {
        let i = rng.gen_range(0..self.challenges.len());
        self.challenges[i].prompt.to_string()
    }

    fn verify(&self, prompt: &str, completion: &str) -> Verdict {
        let challenge = match self.challenge_for_prompt(prompt) {
            Some(c) => c,
            None => {
                return Verdict::Inconclusive {
                    reason: format!("unknown prompt: {prompt:?}"),
                }
            }
        };
        if let Err(e) = self.write_program(prompt, completion, challenge.suffix) {
            return Verdict::Inconclusive {
                reason: format!("write failed: {e}"),
            };
        }
        match self.run_cargo(self.run_program) {
            Ok(out) if out.success => Verdict::Correct,
            Ok(out) => Verdict::Incorrect {
                reason: format!(
                    "cargo {} failed in {:?}: {}",
                    if self.run_program { "run" } else { "check" },
                    out.elapsed,
                    out.stderr_tail
                ),
            },
            Err(e) => Verdict::Inconclusive {
                reason: format!("cargo invoke failed: {e}"),
            },
        }
    }

    fn charset(&self) -> &str {
        // Rust char-level training is impractical; this charset is mostly a
        // hint. Real use of RustCodeDomain pairs it with a BPE tokenizer.
        " \n\t!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("rust_code_test_{name}"));
        let _ = fs::remove_dir_all(&dir);
        dir
    }

    #[test]
    fn correct_completion_passes() {
        let dir = scratch_dir("ok");
        let d = RustCodeDomain::new(&dir);
        d.ensure_scratch_project().unwrap();
        let v = d.verify("fn main() { assert_eq!(", "2 + 3");
        assert!(matches!(v, Verdict::Correct), "got: {v:?}");
    }

    #[test]
    fn wrong_completion_fails() {
        let dir = scratch_dir("nope");
        let d = RustCodeDomain::new(&dir);
        d.ensure_scratch_project().unwrap();
        // Wrong answer (assert_eq!(2 + 4, 5) → panics at runtime).
        let v = d.verify("fn main() { assert_eq!(", "2 + 4");
        assert!(matches!(v, Verdict::Incorrect { .. }), "got: {v:?}");
    }

    #[test]
    fn unknown_prompt_inconclusive() {
        let dir = scratch_dir("unknown");
        let d = RustCodeDomain::new(&dir);
        d.ensure_scratch_project().unwrap();
        let v = d.verify("fn main() { unknown_thing(", "");
        assert!(matches!(v, Verdict::Inconclusive { .. }), "got: {v:?}");
    }
}
